import('./features/load-content-page').then()
import('./features/load-page').then()
import('./features/change-planet').then()
import('./features/menu-animation').then()
import('./features/transition-page').then()
